# This is an example configuration file from my working deployment. Edit to suit
# your configuration.

# Each device on the CAN bus gets an entry describing its address, outputs and
# inputs. Devices will be reported to HomeAssistant.
ground:
  # Device address on the CAN bus
  addr: 1
  outputs:
    bathroom-top:
      id: 1
      # type: light # TODO?
    garage1:
      id: 2
    garage2:
      id: 3
    hall-upstairs:
      id: 4
    hall-res1:
      id: 5
    hall:
      id: 6
    hall-res2:
      id: 7
    office:
      id: 8
    patio-table1:
      id: 9
    patio-table2:
      id: 10
    patio-sconce1:
      id: 11
    patio-sconce2:
      id: 12
    patio-sconce3:
      id: 13
    bathroom-mirror:
      id: 14
    staircase-1:
      id: 15
    staircase-2:
      id: 16

    # # Number of outputs (switchable)
    # count: 8
    # # Outputs can be labeled in the order:
    # labels:
    #   - light1
    #   - light2
    #   - light3
    #   - light4
    #   - light5
    #   - light6
    #   - light7
    #   - light8
  inputs:
    # Can have a number of inputs that are not switchable (binary inputs)
    room1-window:
      id: 1
    room1-door:
      id: 2
    room2-window:
      id: 3
    room2-door:
      id: 4

living-room:
  addr: 2
  outputs:
    kitchen-top:
      id: 1
    wyspa-l:
      id: 2
    wyspa-r:
      id: 3
    dining-table:
      id: 4
    dining-top-l:
      id: 5
    dining-top-r:
      id: 6
    salon-top-l:
      id: 7
    salon-top-r:
      id: 8
    salon-3:
      id: 9
    sconce-1:
      id: 10
    sconce-2:
      id: 11
    sconce-3:
      id: 12
    # 4 empty
  inputs: {}

west:
  # Device address on the CAN bus
  addr: 10
  outputs:
    cza-top1:
      id: 1
    cza-top2:
      id: 2
    cza-sconce:
      id: 3
    ev-top1:
      id: 4
    ev-top2:
      id: 5
    ev-sconce:
      id: 6
    bathroom-top-single:
      id: 7
    bathroom-top-double:
      id: 8
    bathroom-mirror1:
      id: 9
    bathroom-mirror2:
      id: 10
    empty-11:
      id: 11
    empty-12:
      id: 12
    ev-down:
      id: 13
    ev-up:
      id: 14
    cza-down:
      id: 15
    cza-up:
      id: 16
  inputs: {}

east:
  # Device address on the CAN bus
  addr: 11
  outputs:
    bedroom-top1:
      id: 1
    bedroom-top2:
      id: 2
    wishes-top1:
      id: 3
    wishes-top2:
      id: 4
    empty1:
      id: 5
    empty2:
      id: 6
    empty3:
      id: 7
    laundry-top:
      id: 8
    empty4:
      id: 9
    empty5:
      id: 10
    empty6:
      id: 11
    empty7:
      id: 12

    bed-down:
      id: 13
    bed-up:
      id: 14
    wishes-down:
      id: 15
    wishes-up:
      id: 16

  inputs: {}
