# Each device has an entry
living-room:
  # Has address on the bus
  addr: 1
  outputs:
    # Number of outputs (switchable)
    count: 8
    # Outputs can be labeled in the order:
    labels:
      - light1
      - light2
      - light3
      - light4
      - light5
      - light6
      - light7
      - light8
  inputs:
    # Can have a number of inputs that are not switchable (binary inputs)
    count: 4
    # And can be labeled
    labels:
      - room1-window
      - room1-door
      - room2-window
      - room2-door

second-floor:
  addr: 2
  outputs:
    count: 2
    labels: []
  inputs:
    count: 0
    labels: []
